import { readFileSync, writeFileSync } from 'node:fs';
import { ToolLoopAgent, Output, stepCountIs, generateText } from 'ai';
import { openrouter } from '@openrouter/ai-sdk-provider';
import { REVIEW_SCHEMA, SYSTEM_PROMPT, type Review } from './review-schema.ts';

// A list of free models across different providers. Free-tier models are
// individually subject to transient upstream rate limits, so we try them in
// order until one returns a usable review. Override with a comma-separated
// OPENROUTER_MODEL to pin or reorder.
const MODEL_IDS = (
  process.env.OPENROUTER_MODEL ??
  [
    'nvidia/nemotron-3-super-120b-a12b:free',
    'qwen/qwen3-next-80b-a3b-instruct:free',
    'openai/gpt-oss-120b:free',
    'meta-llama/llama-3.3-70b-instruct:free',
  ].join(',')
)
  .split(',')
  .map((s) => s.trim())
  .filter(Boolean);

const DIFF_FILE = process.env.DIFF_FILE ?? 'pr.diff';
const COMMENT_FILE = process.env.COMMENT_FILE ?? 'comment.md';
const MAX_DIFF_CHARS = 50_000;

function readDiff(): string {
  try {
    return readFileSync(DIFF_FILE, 'utf8');
  } catch {
    return '';
  }
}

function buildPrompt(diff: string): string {
  const title = process.env.PR_TITLE || '(no title)';
  const body = process.env.PR_BODY || '(no description)';
  const truncated =
    diff.length > MAX_DIFF_CHARS ? `${diff.slice(0, MAX_DIFF_CHARS)}\n\n[diff truncated]` : diff;
  return `PR title: ${title}\n\nPR description:\n${body}\n\nDiff:\n\n${truncated}`;
}

// Tier 1: agent with enforced structured output.
async function structuredReview(modelId: string, prompt: string): Promise<Review> {
  const agent = new ToolLoopAgent({
    model: openrouter(modelId),
    instructions: SYSTEM_PROMPT,
    output: Output.object({ schema: REVIEW_SCHEMA }),
    stopWhen: stepCountIs(2),
  });
  const result = await agent.generate({ prompt });
  const usage = result.totalUsage;
  if (usage) {
    console.error(
      `[${modelId}] tokens: ${usage.inputTokens ?? '?'} in / ${usage.outputTokens ?? '?'} out`,
    );
  }
  return result.output;
}

function extractJson(text: string): string {
  const fenced = text.match(/```(?:json)?\s*([\s\S]*?)```/);
  const candidate = fenced ? fenced[1] : text;
  const start = candidate.indexOf('{');
  const end = candidate.lastIndexOf('}');
  return start >= 0 && end > start ? candidate.slice(start, end + 1) : candidate;
}

// Tier 2: free models that can't honor strict structured output still tend to emit JSON
// when asked directly; parse and validate it ourselves.
async function jsonFallbackReview(modelId: string, prompt: string): Promise<Review | string> {
  const { text } = await generateText({
    model: openrouter(modelId),
    system: `${SYSTEM_PROMPT}\n\nRespond with ONLY a JSON object with these keys: implementationCorrectness, idiomaticity, complexity, testRiskCoverage, securitySafety (all numbers 1-10), verdict ("pass" or "fail"), summary (string). No markdown fences, no prose.`,
    prompt,
  });
  try {
    const parsed = REVIEW_SCHEMA.safeParse(JSON.parse(extractJson(text)));
    if (parsed.success) return parsed.data;
  } catch {
    // fall through to raw text
  }
  return text;
}

function renderComment(review: Review | string, modelId: string): string {
  if (typeof review === 'string') {
    return [
      '## AI Code Review',
      '',
      `_Model \`${modelId}\` returned unstructured output — posting raw response._`,
      '',
      review,
    ].join('\n');
  }
  const badge = review.verdict === 'pass' ? '✅ PASS' : '❌ FAIL';
  return [
    '## AI Code Review',
    '',
    `**Verdict: ${badge}**`,
    '',
    '| Criterion | Score (1-10) |',
    '| --- | --- |',
    `| Implementation correctness | ${review.implementationCorrectness} |`,
    `| Idiomaticity | ${review.idiomaticity} |`,
    `| Complexity | ${review.complexity} |`,
    `| Test coverage vs risk | ${review.testRiskCoverage} |`,
    `| Security | ${review.securitySafety} |`,
    '',
    '### Summary',
    '',
    review.summary,
    '',
    `<sub>Generated by @habitpair/code-reviewer · model \`${modelId}\`</sub>`,
  ].join('\n');
}

function finish(review: Review | string, modelId: string): void {
  writeFileSync(COMMENT_FILE, renderComment(review, modelId));
  console.log(typeof review === 'string' ? review : JSON.stringify(review, null, 2));
}

async function main(): Promise<void> {
  const diff = readDiff();
  if (!diff.trim()) {
    const empty = '## AI Code Review\n\nNo diff to review (empty diff against the base branch).';
    writeFileSync(COMMENT_FILE, empty);
    console.log(JSON.stringify({ verdict: 'pass', note: 'empty diff' }, null, 2));
    return;
  }

  const prompt = buildPrompt(diff);

  let lastText: string | null = null;
  let lastError: string | null = null;

  for (const modelId of MODEL_IDS) {
    try {
      finish(await structuredReview(modelId, prompt), modelId);
      return;
    } catch (err) {
      console.error(
        `[${modelId}] structured output failed (${(err as Error).message}); trying JSON fallback.`,
      );
      try {
        const result = await jsonFallbackReview(modelId, prompt);
        if (typeof result !== 'string') {
          finish(result, modelId);
          return;
        }
        lastText = result; // unstructured text — keep as a last resort, try the next model
        console.error(`[${modelId}] returned unstructured text; trying next model.`);
      } catch (err2) {
        lastError = (err2 as Error).message;
        console.error(`[${modelId}] JSON fallback failed: ${lastError}`);
      }
    }
  }

  // No model produced a structured review: post the best raw text we got, else the error.
  const lastModel = MODEL_IDS[MODEL_IDS.length - 1] ?? '(none)';
  finish(lastText ?? `Review could not be generated. Last error: ${lastError ?? 'unknown'}`, lastModel);
}

await main();
